### ISSUE TITLE
Using this plugin with nunjucks

### ISSUE THREAD

**Issue by wernerglinka** [ericstiles/metalsmith-wordcloud#4]
Hi Eric,
I am using this plugin with the Nunjucks templating engine. I have a test site with four tags. When I look at the cloud array via 
{{ cloud | dump }} 

I see:
[{"ctg":"[object Object]","wght":9,"pth":"/topics/[object Object]"}]. 

I expected to see:
[{"ctg":"tagName1","wght":1,"pth":"/topics/tagName1"}]
[{"ctg":"tagName2","wght":2,"pth":"/topics/TagName2"}]
[{"ctg":"tagName3","wght":3,"pth":"/topics/TagName3"}]
[{"ctg":"tagName4","wght":4,"pth":"/topics/TagName4"}]

The tags plugin is installed and initialized before wordcloud.

Are you aware of any issues with your plugin when used with Nunjucks?

**Comment by ericstiles** [comment]
Hey Werner-  

Apologize for a delayed response.  

I've haven't kept up recently with metalsmith, so I don't have any good response for you.  Not the best response, but please let me know if you looked any deeper at this.

-Eric

**Comment by wernerglinka** [comment]
Thanks Eric,
I know how that works - I am a freelancer, every project is different. I ended up using a tag module. When my next metalsmith project comes along I'll check this out further.

Werner

**Comment by ericstiles** [comment]
The plugin was recently updated to work with newer versions of metalsmith.  While I can't test this issue directly I believe the root cause was based on changes to metalsmith.
